apiVersion: v1
kind: Namespace
metadata:
  name: sample
  labels:
    prometheus: sample
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: sample
data:
  nginx.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        location /nginx_status {
            stub_status on;
            access_log  on;
            allow all;
        }
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
